<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RevitVersion>2024</RevitVersion>
    <TargetFramework>net48</TargetFramework>
    <RevitApiDir Condition="'$(RevitApiDir)' == ''">C:\Program Files\Autodesk\Revit $(RevitVersion)</RevitApiDir>
    <AssemblyName>IFCInfo</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="IFCInfoCommand.cs" />
    <Compile Include="DuctCreation.cs" />
    <Compile Include="DuctCoverage.cs" />
    <Compile Include="DuctCreationWindow.cs" />
    <Compile Include="IFCInfoWindow.cs" />
    <Compile Include="UiDesign.cs" />
    <Compile Include="IfcSourceReader.cs" />
    <Compile Include="AirTerminalReplacementWindow.cs" />
    <Compile Include="AirTerminalReplacement.cs" />
    <Reference Include="PresentationFramework" />
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <Reference Include="System.Xaml" />
    <Reference Include="RevitAPI">
      <HintPath>$(RevitApiDir)\RevitAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>$(RevitApiDir)\RevitAPIUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>



